name: RPM Build BashPass-Remote
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Pre-requirements
      run: |
        sudo apt update
        sudo apt install -y rpm

    - name: build BashPass-Remote RPM package
      id: rpm
      run: |
        cd bashpass-remote/ || exit 1
        git clone https://github.com/AntonVanAssche/BashPass-Remote.git
        bash build.sh
        cp -r ~/rpmbuild/RPMS/noarch/* .

    - uses: actions/upload-artifact@v2
      with:
        name: rpm
        path: bashpass-remote/bashpass-remote-1.0-1.noarch.rpm

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: rpm

      - uses: AntonVanAssche/yank-packagecloud@v1.0
        continue-on-error: true
        with:
          PACKAGE-NAME: bashpass-remote-1.0-1.noarch.rpm
          PACKAGECLOUD-USERNAME: AntonVanAssche
          PACKAGECLOUD-REPO: bashpass
          PACKAGECLOUD-DISTRIB: fedora/33/
          PACKAGECLOUD-TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}

      - uses: danielmundi/upload-packagecloud@v1
        with:
          PACKAGE-NAME: bashpass-remote-1.0-1.noarch.rpm
          PACKAGECLOUD-USERNAME: AntonVanAssche
          PACKAGECLOUD-REPO: bashpass
          PACKAGECLOUD-DISTRIB: fedora/36/
          PACKAGECLOUD-TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}

      - uses: AntonVanAssche/yank-packagecloud@v1.0
        continue-on-error: true
        with:
          PACKAGE-NAME: bashpass-remote-1.0-1.noarch.rpm
          PACKAGECLOUD-USERNAME: AntonVanAssche
          PACKAGECLOUD-REPO: bashpass
          PACKAGECLOUD-DISTRIB: fedora/37/
          PACKAGECLOUD-TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}

      - uses: danielmundi/upload-packagecloud@v1
        with:
          PACKAGE-NAME: bashpass-remote-1.0-1.noarch.rpm
          PACKAGECLOUD-USERNAME: AntonVanAssche
          PACKAGECLOUD-REPO: bashpass
          PACKAGECLOUD-DISTRIB: fedora/37/
          PACKAGECLOUD-TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
